# packages I'm using so far...

#.First.sys()

cat("loading packages used in project.\n")

library(prettydoc)
library(rmdformats)
library(bookdown)
library(rmdformats)
library(recipes)
library(themis)
library(tidyverse)
library(skimr)
library(ggplot2)
library(ggthemes)
library(gridExtra)
library(ggrepel)
library(grid)
library(ggpubr)
library(knitr)
library(RColorBrewer)
library(MASS)
library(dplyr)
library(DBI)
library(dbplyr)
library(odbc)
library(forecast)
library(caret)
library(data.table)
library(tidyr)
library(tidyverse)
library(plm)
library(lubridate)
library(foreach)
library(coefplot)
library(ModelMetrics)
library(zoo)
library(tibbletime)
library(timetk)
library(timeDate)
library(seasonal)
library(conflicted)
library(fable)
library(tsibble)
library(naniar)
library(corrplot)
library(broom)
library(readxl)
library(factoextra)
library(ggfortify)
library(ggcorrplot)
library(GGally)
library(tidytext)
library(flextable)
library(scales)
library(DT)
library(wesanderson)
library(viridis)
library(reshape2)
library(feasts)
library(webshot)
library(yardstick)
library(ggridges)
library(butcher)
library(discrim)
library(hardhat)
library(probably)
library(fuzzyjoin)
library(modeltime)
library(e1071)
library(magrittr)
library(tidymodels)
library(rsample)
library(workflows)
library(ggforce)
library(flextable)

require(prettydoc)
require(rmdformats)
require(bookdown)
require(rmdformats)
require(recipes)
require(tidyverse)
require(skimr)
require(ggplot2)
require(ggthemes)
require(gridExtra)
require(ggrepel)
require(grid)
require(ggpubr)
require(knitr)
require(RColorBrewer)
require(MASS)
require(dplyr)
require(DBI)
require(dbplyr)
require(odbc)
require(forecast)
require(caret)
require(data.table)
require(tidyr)
require(tidyverse)
require(plm)
require(lubridate)
require(foreach)
require(coefplot)
require(ModelMetrics)
require(zoo)
require(tibbletime)
require(timetk)
require(timeDate)
require(seasonal)
require(conflicted)
require(fable)
require(tsibble)
require(naniar)
require(corrplot)
require(broom)
require(readxl)
require(factoextra)
require(ggfortify)
require(ggcorrplot)
require(GGally)
require(tidytext)
require(flextable)
require(scales)
require(DT)
require(wesanderson)
require(viridis)
require(reshape2)
require(feasts)
require(webshot)
require(themis)
require(yardstick)
require(ggridges)
require(butcher)
require(discrim)
require(hardhat)
require(probably)
require(fuzzyjoin)
require(modeltime)
require(e1071)
require(magrittr)
require(tidymodels)
require(workflows)
require(rsample)
require(ggforce)
require(flextable)

cat("setting conflict preferences.\n")

conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("replace_na", "tidyr")
conflict_prefer("summarize", "dplyr")
conflict_prefer("year", "lubridate")
conflict_prefer("quarter", "lubridate")
conflict_prefer("compose", "flextable")
conflict_prefer("melt", "reshape2")
conflict_prefer("set_names", "magrittr")
conflict_prefer("flatten", "purrr")
conflict_prefer("tune", "tune")


##file.create(".Rprofile.")
#file.edit(".Rprofile")
