
# 2018
divisions_2018 = 
        tibble(SEASON = 2018,
               CONFERENCE = "SEC",
               CONFERENCE_DIVISION = c("East"),
               TEAM = c("Florida",
                        "Georgia",
                        "Kentucky",
                        "Missouri",
                        "South Carolina",
                        "Tennessee",
                        "Vanderbilt")) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = "SEC",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Alabama",
                                  "Arkansas",
                                  "Auburn",
                                  "LSU",
                                  "Mississippi State",
                                  "Ole Miss",
                                  "Texas A&M"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = "Big Ten",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Illinois", 
                                  "Iowa", 
                                  "Minnesota",
                                  "Nebraska",
                                  "Northwestern",
                                  "Purdue",
                                  "Wisconsin"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = "Big Ten",
                         CONFERENCE_DIVISION = "East",
                         TEAM = c("Indiana",
                                  "Maryland",
                                  "Michigan",
                                  "Michigan State",
                                  "Ohio State",
                                  "Penn State",
                                  "Rutgers"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = "ACC",
                         CONFERENCE_DIVISION = "Atlantic",
                         TEAM = c("Boston College",
                                  "Clemson",
                                  "Florida State",
                                  "Louisville",
                                  "NC State",
                                  "Syracuse",
                                  "Wake Forest"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = "ACC",
                         CONFERENCE_DIVISION = "Coastal",
                         TEAM = c("Duke",
                                  "Georgia Tech",
                                  "Miami",
                                  "North Carolina",
                                  "Pittsburgh",
                                  "Virginia",
                                  "Virginia Tech"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = "Mid-American",
                         CONFERENCE_DIVISION = "East",
                         TEAM = c("Akron",
                                  "Bowling Green",
                                  "Buffalo", 
                                  "Kent State",
                                  "Miami (OH)",
                                  "Ohio"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = "Mid-American",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Ball State",
                                  "Central Michigan",
                                  "Eastern Michigan",
                                  "Northern Illinois",
                                  "Toledo",
                                  "Western Michigan"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = "Mountain West",
                         CONFERENCE_DIVISION = "Mountain",
                         TEAM = c("Air Force",
                                  "Boise State",
                                  "Colorado State",
                                  "New Mexico",
                                  "Utah State",
                                  "Wyoming"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = "Mountain West",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Fresno State",
                                  "Hawai'i",
                                  "Nevada",
                                  "San Diego State",
                                  "San José State",
                                  "UNLV"))) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = "Sun Belt",
                         CONFERENCE_DIVISION = "East",
                         TEAM = c("Appalachian State",
                                  "Coastal Carolina",
                                  "Georgia Southern",
                                  "Troy",
                                  "Georgia State"))
        ) %>% 
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = "Sun Belt",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Arkansas State",
                                  "Louisiana",
                                  "Louisiana Monroe",
                                  "South Alabama",
                                  "Texas State"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = 'Big 12',
                         TEAM = c("Baylor",
                                  "Iowa State",
                                  "Kansas State",
                                  "Kansas",
                                  "Oklahoma",
                                  "Oklahoma State",
                                  "TCU",
                                  "Texas",
                                  "Texas Tech",
                                  "West Virginia"))) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = 'Pac-12',
                         CONFERENCE_DIVISION = "North",
                         TEAM = c("California",
                                  "Oregon",
                                  "Oregon State",
                                  "Washington",
                                  "Washington State",
                                  "Stanford"))) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = 'Pac-12',
                         CONFERENCE_DIVISION = "South",
                         TEAM = c("Arizona",
                                  "Arizona State",
                                  "Colorado",
                                  "UCLA",
                                  "USC",
                                  "Utah"))) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = 'Conference USA',
                         TEAM = c("Charlotte",
                                  "Florida Atlantic",
                                  "Florida International",
                                  "Louisiana Tech",
                                  "Middle Tennessee",
                                  "Marshall",
                                  "North Texas",
                                  "Rice",
                                  "Old Dominion",
                                  "UAB",
                                  "UTEP",
                                  "UT San Antonio",
                                  "Southern Mississippi",
                                  "Western Kentucky"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = 'American Athletic',
                         TEAM = c("Cincinnati",
                                  "East Carolina",
                                  "Houston",
                                  "Memphis",
                                  "Navy",
                                  "SMU",
                                  "South Florida",
                                  "Temple",
                                  "Tulane",
                                  "Tulsa",
                                  "UCF"
                         ))) %>%
        bind_rows(.,
                  tibble(SEASON = 2018,
                         CONFERENCE = 'FBS Independents',
                         TEAM = c("Army",
                                  "BYU",
                                  "Liberty",
                                  "New Mexico State",
                                  "Notre Dame",
                                  "Connecticut",
                                  "UMass")))


# 2019
divisions_2019 = 
        tibble(SEASON = 2019,
               CONFERENCE = "SEC",
               CONFERENCE_DIVISION = c("East"),
               TEAM = c("Florida",
                        "Georgia",
                        "Kentucky",
                        "Missouri",
                        "South Carolina",
                        "Tennessee",
                        "Vanderbilt")) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = "SEC",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Alabama",
                                  "Arkansas",
                                  "Auburn",
                                  "LSU",
                                  "Mississippi State",
                                  "Ole Miss",
                                  "Texas A&M"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = "Big Ten",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Illinois", 
                                  "Iowa", 
                                  "Minnesota",
                                  "Nebraska",
                                  "Northwestern",
                                  "Purdue",
                                  "Wisconsin"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = "Big Ten",
                         CONFERENCE_DIVISION = "East",
                         TEAM = c("Indiana",
                                  "Maryland",
                                  "Michigan",
                                  "Michigan State",
                                  "Ohio State",
                                  "Penn State",
                                  "Rutgers"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = "ACC",
                         CONFERENCE_DIVISION = "Atlantic",
                         TEAM = c("Boston College",
                                  "Clemson",
                                  "Florida State",
                                  "Louisville",
                                  "NC State",
                                  "Syracuse",
                                  "Wake Forest"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = "ACC",
                         CONFERENCE_DIVISION = "Coastal",
                         TEAM = c("Duke",
                                  "Georgia Tech",
                                  "Miami",
                                  "North Carolina",
                                  "Pittsburgh",
                                  "Virginia",
                                  "Virginia Tech"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = "Mid-American",
                         CONFERENCE_DIVISION = "East",
                         TEAM = c("Akron",
                                  "Bowling Green",
                                  "Buffalo", 
                                  "Kent State",
                                  "Miami (OH)",
                                  "Ohio"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = "Mid-American",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Ball State",
                                  "Central Michigan",
                                  "Eastern Michigan",
                                  "Northern Illinois",
                                  "Toledo",
                                  "Western Michigan"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = "Mountain West",
                         CONFERENCE_DIVISION = "Mountain",
                         TEAM = c("Air Force",
                                  "Boise State",
                                  "Colorado State",
                                  "New Mexico",
                                  "Utah State",
                                  "Wyoming"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = "Mountain West",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Fresno State",
                                  "Hawai'i",
                                  "Nevada",
                                  "San Diego State",
                                  "San José State",
                                  "UNLV"))) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = "Sun Belt",
                         CONFERENCE_DIVISION = "East",
                         TEAM = c("Appalachian State",
                                  "Coastal Carolina",
                                  "Georgia Southern",
                                  "Troy",
                                  "Georgia State"))
        ) %>% 
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = "Sun Belt",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Arkansas State",
                                  "Louisiana",
                                  "Louisiana Monroe",
                                  "South Alabama",
                                  "Texas State"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = 'Big 12',
                         TEAM = c("Baylor",
                                  "Iowa State",
                                  "Kansas State",
                                  "Kansas",
                                  "Oklahoma",
                                  "Oklahoma State",
                                  "TCU",
                                  "Texas",
                                  "Texas Tech",
                                  "West Virginia"))) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = 'Pac-12',
                         CONFERENCE_DIVISION = "North",
                         TEAM = c("California",
                                  "Oregon",
                                  "Oregon State",
                                  "Washington",
                                  "Washington State",
                                  "Stanford"))) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = 'Pac-12',
                         CONFERENCE_DIVISION = "South",
                         TEAM = c("Arizona",
                                  "Arizona State",
                                  "Colorado",
                                  "UCLA",
                                  "USC",
                                  "Utah"))) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = 'Conference USA',
                         TEAM = c("Charlotte",
                                  "Florida Atlantic",
                                  "Florida International",
                                  "Louisiana Tech",
                                  "Middle Tennessee",
                                  "Marshall",
                                  "North Texas",
                                  "Rice",
                                  "Old Dominion",
                                  "UAB",
                                  "UTEP",
                                  "UT San Antonio",
                                  "Southern Mississippi",
                                  "Western Kentucky"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = 'American Athletic',
                         TEAM = c("Cincinnati",
                                  "East Carolina",
                                  "Houston",
                                  "Memphis",
                                  "Navy",
                                  "SMU",
                                  "South Florida",
                                  "Temple",
                                  "Tulane",
                                  "Tulsa",
                                  "UCF"
                         ))) %>%
        bind_rows(.,
                  tibble(SEASON = 2019,
                         CONFERENCE = 'FBS Independents',
                         TEAM = c("Army",
                                  "BYU",
                                  "Liberty",
                                  "New Mexico State",
                                  "Notre Dame",
                                  "Connecticut",
                                  "UMass")))


# 2021
divisions_2021 = 
        tibble(SEASON = 2021,
               CONFERENCE = "SEC",
               CONFERENCE_DIVISION = c("East"),
               TEAM = c("Florida",
                        "Georgia",
                        "Kentucky",
                        "Missouri",
                        "South Carolina",
                        "Tennessee",
                        "Vanderbilt")) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = "SEC",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Alabama",
                                  "Arkansas",
                                  "Auburn",
                                  "LSU",
                                  "Mississippi State",
                                  "Ole Miss",
                                  "Texas A&M"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = "Big Ten",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Illinois", 
                                  "Iowa", 
                                  "Minnesota",
                                  "Nebraska",
                                  "Northwestern",
                                  "Purdue",
                                  "Wisconsin"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = "Big Ten",
                         CONFERENCE_DIVISION = "East",
                         TEAM = c("Indiana",
                                  "Maryland",
                                  "Michigan",
                                  "Michigan State",
                                  "Ohio State",
                                  "Penn State",
                                  "Rutgers"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = "ACC",
                         CONFERENCE_DIVISION = "Atlantic",
                         TEAM = c("Boston College",
                                  "Clemson",
                                  "Florida State",
                                  "Louisville",
                                  "NC State",
                                  "Syracuse",
                                  "Wake Forest"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = "ACC",
                         CONFERENCE_DIVISION = "Coastal",
                         TEAM = c("Duke",
                                  "Georgia Tech",
                                  "Miami",
                                  "North Carolina",
                                  "Pittsburgh",
                                  "Virginia",
                                  "Virginia Tech"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = "Mid-American",
                         CONFERENCE_DIVISION = "East",
                         TEAM = c("Akron",
                                  "Bowling Green",
                                  "Buffalo", 
                                  "Kent State",
                                  "Miami (OH)",
                                  "Ohio"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = "Mid-American",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Ball State",
                                  "Central Michigan",
                                  "Eastern Michigan",
                                  "Northern Illinois",
                                  "Toledo",
                                  "Western Michigan"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = "Mountain West",
                         CONFERENCE_DIVISION = "Mountain",
                         TEAM = c("Air Force",
                                  "Boise State",
                                  "Colorado State",
                                  "New Mexico",
                                  "Utah State",
                                  "Wyoming"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = "Mountain West",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Fresno State",
                                  "Hawai'i",
                                  "Nevada",
                                  "San Diego State",
                                  "San José State",
                                  "UNLV"))) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = "Sun Belt",
                         CONFERENCE_DIVISION = "East",
                         TEAM = c("Appalachian State",
                                  "Coastal Carolina",
                                  "Georgia Southern",
                                  "Troy",
                                  "Georgia State"))
        ) %>% 
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = "Sun Belt",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Arkansas State",
                                  "Louisiana",
                                  "Louisiana Monroe",
                                  "South Alabama",
                                  "Texas State"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = 'Big 12',
                         TEAM = c("Baylor",
                                  "Iowa State",
                                  "Kansas State",
                                  "Kansas",
                                  "Oklahoma",
                                  "Oklahoma State",
                                  "TCU",
                                  "Texas",
                                  "Texas Tech",
                                  "West Virginia"))) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = 'Pac-12',
                         CONFERENCE_DIVISION = "North",
                         TEAM = c("California",
                                  "Oregon",
                                  "Oregon State",
                                  "Washington",
                                  "Washington State",
                                  "Stanford"))) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = 'Pac-12',
                         CONFERENCE_DIVISION = "South",
                         TEAM = c("Arizona",
                                  "Arizona State",
                                  "Colorado",
                                  "UCLA",
                                  "USC",
                                  "Utah"))) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = 'Conference USA',
                         TEAM = c("Charlotte",
                                  "Florida Atlantic",
                                  "Florida International",
                                  "Louisiana Tech",
                                  "Middle Tennessee",
                                  "Marshall",
                                  "North Texas",
                                  "Rice",
                                  "Old Dominion",
                                  "UAB",
                                  "UTEP",
                                  "UT San Antonio",
                                  "Southern Mississippi",
                                  "Western Kentucky"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = 'American Athletic',
                         TEAM = c("Cincinnati",
                                  "East Carolina",
                                  "Houston",
                                  "Memphis",
                                  "Navy",
                                  "SMU",
                                  "South Florida",
                                  "Temple",
                                  "Tulane",
                                  "Tulsa",
                                  "UCF"
                         ))) %>%
        bind_rows(.,
                  tibble(SEASON = 2021,
                         CONFERENCE = 'FBS Independents',
                         TEAM = c("Army",
                                  "BYU",
                                  "Liberty",
                                  "New Mexico State",
                                  "Notre Dame",
                                  "Connecticut",
                                  "UMass")))

# 2022
# set up conference divisions
divisions_2022 = 
        tibble(SEASON = 2022,
               CONFERENCE = "SEC",
               CONFERENCE_DIVISION = c("East"),
               TEAM = c("Florida",
                        "Georgia",
                        "Kentucky",
                        "Missouri",
                        "South Carolina",
                        "Tennessee",
                        "Vanderbilt")) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = "SEC",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Alabama",
                                  "Arkansas",
                                  "Auburn",
                                  "LSU",
                                  "Mississippi State",
                                  "Ole Miss",
                                  "Texas A&M"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = "Big Ten",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Illinois", 
                                  "Iowa", 
                                  "Minnesota",
                                  "Nebraska",
                                  "Northwestern",
                                  "Purdue",
                                  "Wisconsin"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = "Big Ten",
                         CONFERENCE_DIVISION = "East",
                         TEAM = c("Indiana",
                                  "Maryland",
                                  "Michigan",
                                  "Michigan State",
                                  "Ohio State",
                                  "Penn State",
                                  "Rutgers"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = "ACC",
                         CONFERENCE_DIVISION = "Atlantic",
                         TEAM = c("Boston College",
                                  "Clemson",
                                  "Florida State",
                                  "Louisville",
                                  "NC State",
                                  "Syracuse",
                                  "Wake Forest"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = "ACC",
                         CONFERENCE_DIVISION = "Coastal",
                         TEAM = c("Duke",
                                  "Georgia Tech",
                                  "Miami",
                                  "North Carolina",
                                  "Pittsburgh",
                                  "Virginia",
                                  "Virginia Tech"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = "Mid-American",
                         CONFERENCE_DIVISION = "East",
                         TEAM = c("Akron",
                                  "Bowling Green",
                                  "Buffalo", 
                                  "Kent State",
                                  "Miami (OH)",
                                  "Ohio"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = "Mid-American",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Ball State",
                                  "Central Michigan",
                                  "Eastern Michigan",
                                  "Northern Illinois",
                                  "Toledo",
                                  "Western Michigan"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = "Mountain West",
                         CONFERENCE_DIVISION = "Mountain",
                         TEAM = c("Air Force",
                                  "Boise State",
                                  "Colorado State",
                                  "New Mexico",
                                  "Utah State",
                                  "Wyoming"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = "Mountain West",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Fresno State",
                                  "Hawai'i",
                                  "Nevada",
                                  "San Diego State",
                                  "San José State",
                                  "UNLV"))) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = "Sun Belt",
                         CONFERENCE_DIVISION = "East",
                         TEAM = c("Appalachian State",
                                  "Coastal Carolina",
                                  "Georgia Southern",
                                  "Georgia State",
                                  "James Madison",
                                  "Marshall",
                                  "Old Dominion"))
        ) %>% 
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = "Sun Belt",
                         CONFERENCE_DIVISION = "West",
                         TEAM = c("Arkansas State",
                                  "Louisiana",
                                  "Louisiana Monroe",
                                  "South Alabama",
                                  "Southern Mississippi",
                                  "Texas State",
                                  "Troy"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = 'Big 12',
                         TEAM = c("Baylor",
                                  "Iowa State",
                                  "Kansas State",
                                  "Kansas",
                                  "Oklahoma",
                                  "Oklahoma State",
                                  "TCU",
                                  "Texas",
                                  "Texas Tech",
                                  "West Virginia"))) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = 'Pac-12',
                         TEAM = c("Arizona",
                                  "Arizona State",
                                  "California",
                                  "Colorado",
                                  "Oregon",
                                  "Oregon State",
                                  "Stanford",
                                  "UCLA",
                                  "USC",
                                  "Utah",
                                  "Washington",
                                  "Washington State"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = 'Conference USA',
                         TEAM = c("Charlotte",
                                  "Florida Atlantic",
                                  "Florida International",
                                  "Louisiana Tech",
                                  "Middle Tennessee",
                                  "North Texas",
                                  "Rice",
                                  "UAB",
                                  "UTEP",
                                  "UT San Antonio",
                                  "Western Kentucky"))
        ) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = 'American Athletic',
                         TEAM = c("Cincinnati",
                                  "East Carolina",
                                  "Houston",
                                  "Memphis",
                                  "Navy",
                                  "SMU",
                                  "South Florida",
                                  "Temple",
                                  "Tulane",
                                  "Tulsa",
                                  "UCF"
                         ))) %>%
        bind_rows(.,
                  tibble(SEASON = 2022,
                         CONFERENCE = 'FBS Independents',
                         TEAM = c("Army",
                                  "BYU",
                                  "Liberty",
                                  "New Mexico State",
                                  "Notre Dame",
                                  "Connecticut",
                                  "UMass")))


# combine
season_conference_divisions = bind_rows(divisions_2018,
                                        divisions_2019,
                                        divisions_2021,
                                        divisions_2022)

# save locally
save(season_conference_divisions,
     file = here::here("data", "season_conference_divisions.Rdata"))


